// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package database

import (
	"context"
	"database/sql"
)

const getCohesionRows = `-- name: GetCohesionRows :many
SELECT p.id AS party_id, p.short_name, iv.votation_id, v.vote_date, iv.vote, COUNT(*) AS n
FROM individual_votes iv
JOIN votations v ON v.id = iv.votation_id
JOIN representative_parties rp
  ON rp.representative_id = iv.representative_id
 AND rp.start_date <= v.vote_date
 AND (rp.end_date IS NULL OR rp.end_date >= v.vote_date)
JOIN parties p ON p.id = rp.party_id
WHERE v.chamber_id = ?1
  AND iv.vote IN ('yes', 'no', 'abstain')
  AND (CAST(?2 AS TEXT) = '' OR v.vote_date >= CAST(?2 AS TEXT))
  AND (CAST(?3 AS TEXT) = '' OR v.vote_date <= CAST(?3 AS TEXT))
  AND (CAST(?4 AS INTEGER) = 0 OR p.id = CAST(?4 AS INTEGER))
GROUP BY p.id, iv.votation_id, iv.vote
ORDER BY v.vote_date
`

type GetCohesionRowsParams struct {
	Chamber  string `json:"chamber"`
	FromDate string `json:"from_date"`
	ToDate   string `json:"to_date"`
	PartyID  int64  `json:"party_id"`
}

type GetCohesionRowsRow struct {
	PartyID    int64  `json:"party_id"`
	ShortName  string `json:"short_name"`
	VotationID int64  `json:"votation_id"`
	VoteDate   string `json:"vote_date"`
	Vote       string `json:"vote"`
	N          int64  `json:"n"`
}

// Per-(party, votation) CAST-vote counts in a chamber + [from,to] vote_date
// window (empty string = open bound), optional party filter (0 = all).
// Cast votes only (yes/no/abstain): absent/dispensed/paired are not
// positions and are excluded from every Rice aggregate (DESIGN.md gap 8).
func (q *Queries) GetCohesionRows(ctx context.Context, arg GetCohesionRowsParams) ([]GetCohesionRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCohesionRows,
		arg.Chamber,
		arg.FromDate,
		arg.ToDate,
		arg.PartyID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCohesionRowsRow{}
	for rows.Next() {
		var i GetCohesionRowsRow
		if err := rows.Scan(
			&i.PartyID,
			&i.ShortName,
			&i.VotationID,
			&i.VoteDate,
			&i.Vote,
			&i.N,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLoyaltyRows = `-- name: GetLoyaltyRows :many
SELECT iv.representative_id AS rep_id,
       r.first_name, r.last_name, r.second_last_name,
       p.id AS party_id, p.short_name AS party_short,
       iv.votation_id, v.vote_date, iv.vote
FROM individual_votes iv
JOIN votations v ON v.id = iv.votation_id
JOIN representatives r ON r.id = iv.representative_id
JOIN representative_parties rp
  ON rp.representative_id = iv.representative_id
 AND rp.start_date <= v.vote_date
 AND (rp.end_date IS NULL OR rp.end_date >= v.vote_date)
JOIN parties p ON p.id = rp.party_id
WHERE v.chamber_id = ?1
  AND iv.vote IN ('yes', 'no', 'abstain')
  AND (CAST(?2 AS TEXT) = '' OR v.vote_date >= CAST(?2 AS TEXT))
  AND (CAST(?3 AS TEXT) = '' OR v.vote_date <= CAST(?3 AS TEXT))
`

type GetLoyaltyRowsParams struct {
	Chamber  string `json:"chamber"`
	FromDate string `json:"from_date"`
	ToDate   string `json:"to_date"`
}

type GetLoyaltyRowsRow struct {
	RepID          int64  `json:"rep_id"`
	FirstName      string `json:"first_name"`
	LastName       string `json:"last_name"`
	SecondLastName string `json:"second_last_name"`
	PartyID        int64  `json:"party_id"`
	PartyShort     string `json:"party_short"`
	VotationID     int64  `json:"votation_id"`
	VoteDate       string `json:"vote_date"`
	Vote           string `json:"vote"`
}

// Rep-level cast votes with party-at-date in the window. Feeds the
// loyalty/'rebels' arithmetic: per (party, votation) modal vote across ALL
// party members, then each rep's vote compared against it.
func (q *Queries) GetLoyaltyRows(ctx context.Context, arg GetLoyaltyRowsParams) ([]GetLoyaltyRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLoyaltyRows, arg.Chamber, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLoyaltyRowsRow{}
	for rows.Next() {
		var i GetLoyaltyRowsRow
		if err := rows.Scan(
			&i.RepID,
			&i.FirstName,
			&i.LastName,
			&i.SecondLastName,
			&i.PartyID,
			&i.PartyShort,
			&i.VotationID,
			&i.VoteDate,
			&i.Vote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPairAgreementRows = `-- name: GetPairAgreementRows :many
SELECT a.representative_id AS a_id, b.representative_id AS b_id,
       COUNT(*) AS joint,
       SUM(CASE WHEN a.vote = b.vote THEN 1 ELSE 0 END) AS same
FROM individual_votes a
JOIN individual_votes b
  ON b.votation_id = a.votation_id AND a.representative_id < b.representative_id
JOIN votations v ON v.id = a.votation_id
WHERE v.chamber_id = ?1
  AND a.vote IN ('yes', 'no', 'abstain')
  AND b.vote IN ('yes', 'no', 'abstain')
  AND (CAST(?2 AS TEXT) = '' OR v.vote_date >= CAST(?2 AS TEXT))
  AND (CAST(?3 AS TEXT) = '' OR v.vote_date <= CAST(?3 AS TEXT))
  AND (CAST(?4 AS INTEGER) = 0 OR EXISTS (
        SELECT 1 FROM representative_parties rpa JOIN parties pa ON pa.id = rpa.party_id
        WHERE rpa.representative_id = a.representative_id AND pa.id = CAST(?4 AS INTEGER)
          AND rpa.start_date <= v.vote_date
          AND (rpa.end_date IS NULL OR rpa.end_date >= v.vote_date)))
  AND (CAST(?4 AS INTEGER) = 0 OR EXISTS (
        SELECT 1 FROM representative_parties rpb JOIN parties pb ON pb.id = rpb.party_id
        WHERE rpb.representative_id = b.representative_id AND pb.id = CAST(?4 AS INTEGER)
          AND rpb.start_date <= v.vote_date
          AND (rpb.end_date IS NULL OR rpb.end_date >= v.vote_date)))
GROUP BY a.representative_id, b.representative_id
`

type GetPairAgreementRowsParams struct {
	Chamber  string `json:"chamber"`
	FromDate string `json:"from_date"`
	ToDate   string `json:"to_date"`
	PartyID  int64  `json:"party_id"`
}

type GetPairAgreementRowsRow struct {
	AID   int64           `json:"a_id"`
	BID   int64           `json:"b_id"`
	Joint int64           `json:"joint"`
	Same  sql.NullFloat64 `json:"same"`
}

// Pairwise same-cast-vote counts for the alignment matrix: deputy pairs that
// were both present (cast) on the same votation, how often they agreed.
// Optional party filter applies party-at-date to BOTH pair members.
func (q *Queries) GetPairAgreementRows(ctx context.Context, arg GetPairAgreementRowsParams) ([]GetPairAgreementRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPairAgreementRows,
		arg.Chamber,
		arg.FromDate,
		arg.ToDate,
		arg.PartyID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPairAgreementRowsRow{}
	for rows.Next() {
		var i GetPairAgreementRowsRow
		if err := rows.Scan(
			&i.AID,
			&i.BID,
			&i.Joint,
			&i.Same,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPartyVoteCounts = `-- name: GetPartyVoteCounts :many
SELECT p.id AS party_id, p.short_name, p.name AS party_name, p.color,
       iv.vote AS vote, COUNT(*) AS n
FROM individual_votes iv
JOIN representatives r ON r.id = iv.representative_id
JOIN votations v ON v.id = iv.votation_id
JOIN representative_parties rp
    ON rp.representative_id = r.id
   AND rp.start_date <= v.vote_date
   AND (rp.end_date IS NULL OR rp.end_date >= v.vote_date)
JOIN parties p ON p.id = rp.party_id
WHERE iv.votation_id = ?
GROUP BY p.id, iv.vote
`

type GetPartyVoteCountsRow struct {
	PartyID   int64  `json:"party_id"`
	ShortName string `json:"short_name"`
	PartyName string `json:"party_name"`
	Color     string `json:"color"`
	Vote      string `json:"vote"`
	N         int64  `json:"n"`
}

// Per-party vote counts for one votation (party-at-date join). Consumed by
// the breakdown chart and, in Phase 2, the Rice-cohesion arithmetic.
func (q *Queries) GetPartyVoteCounts(ctx context.Context, votationID int64) ([]GetPartyVoteCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPartyVoteCounts, votationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPartyVoteCountsRow{}
	for rows.Next() {
		var i GetPartyVoteCountsRow
		if err := rows.Scan(
			&i.PartyID,
			&i.ShortName,
			&i.PartyName,
			&i.Color,
			&i.Vote,
			&i.N,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
