// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package database

import (
	"context"
)

const getPartyVoteCounts = `-- name: GetPartyVoteCounts :many
SELECT p.id AS party_id, p.short_name, p.name AS party_name, p.color,
       iv.vote AS vote, COUNT(*) AS n
FROM individual_votes iv
JOIN representatives r ON r.id = iv.representative_id
JOIN votations v ON v.id = iv.votation_id
JOIN representative_parties rp
    ON rp.representative_id = r.id
   AND rp.start_date <= v.vote_date
   AND (rp.end_date IS NULL OR rp.end_date >= v.vote_date)
JOIN parties p ON p.id = rp.party_id
WHERE iv.votation_id = ?
GROUP BY p.id, iv.vote
`

type GetPartyVoteCountsRow struct {
	PartyID   int64  `json:"party_id"`
	ShortName string `json:"short_name"`
	PartyName string `json:"party_name"`
	Color     string `json:"color"`
	Vote      string `json:"vote"`
	N         int64  `json:"n"`
}

// Per-party vote counts for one votation (party-at-date join). Consumed by
// the breakdown chart and, in Phase 2, the Rice-cohesion arithmetic.
func (q *Queries) GetPartyVoteCounts(ctx context.Context, votationID int64) ([]GetPartyVoteCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPartyVoteCounts, votationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPartyVoteCountsRow{}
	for rows.Next() {
		var i GetPartyVoteCountsRow
		if err := rows.Scan(
			&i.PartyID,
			&i.ShortName,
			&i.PartyName,
			&i.Color,
			&i.Vote,
			&i.N,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
