// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bills.sql

package database

import (
	"context"
	"database/sql"
)

const countBills = `-- name: CountBills :one
SELECT COUNT(*) FROM bills WHERE id LIKE ?
`

func (q *Queries) CountBills(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBills, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBill = `-- name: GetBill :one
SELECT id, title, title_source, title_date, status, law_number, filed_date FROM bills WHERE id = ?
`

func (q *Queries) GetBill(ctx context.Context, id string) (Bill, error) {
	row := q.db.QueryRowContext(ctx, getBill, id)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TitleSource,
		&i.TitleDate,
		&i.Status,
		&i.LawNumber,
		&i.FiledDate,
	)
	return i, err
}

const getVotationsByBill = `-- name: GetVotationsByBill :many
SELECT id, chamber_id, external_id, session_id, bill_id, date, vote_date, subject, vote_type, result, quorum_type, legislative_step, total_yes, total_no, total_abstain, total_dispensed FROM votations WHERE bill_id = ? ORDER BY date DESC
`

func (q *Queries) GetVotationsByBill(ctx context.Context, billID sql.NullString) ([]Votation, error) {
	rows, err := q.db.QueryContext(ctx, getVotationsByBill, billID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Votation{}
	for rows.Next() {
		var i Votation
		if err := rows.Scan(
			&i.ID,
			&i.ChamberID,
			&i.ExternalID,
			&i.SessionID,
			&i.BillID,
			&i.Date,
			&i.VoteDate,
			&i.Subject,
			&i.VoteType,
			&i.Result,
			&i.QuorumType,
			&i.LegislativeStep,
			&i.TotalYes,
			&i.TotalNo,
			&i.TotalAbstain,
			&i.TotalDispensed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBills = `-- name: ListBills :many
SELECT id, title, title_source, title_date, status, law_number, filed_date FROM bills
WHERE id LIKE ?
ORDER BY title_date DESC
LIMIT ? OFFSET ?
`

type ListBillsParams struct {
	ID     string `json:"id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

// matches with a caller-supplied pattern ('%term%' built in Go)
func (q *Queries) ListBills(ctx context.Context, arg ListBillsParams) ([]Bill, error) {
	rows, err := q.db.QueryContext(ctx, listBills, arg.ID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bill{}
	for rows.Next() {
		var i Bill
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TitleSource,
			&i.TitleDate,
			&i.Status,
			&i.LawNumber,
			&i.FiledDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBillStub = `-- name: UpsertBillStub :exec
INSERT INTO bills (id, title, title_source, title_date)
VALUES (?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    title = excluded.title,
    title_source = excluded.title_source,
    title_date = excluded.title_date
`

type UpsertBillStubParams struct {
	ID          string         `json:"id"`
	Title       string         `json:"title"`
	TitleSource string         `json:"title_source"`
	TitleDate   sql.NullString `json:"title_date"`
}

// Title upgrade policy is decided in Go (most-recent-votation Articulo wins);
// the caller passes the chosen title/source/date. Placeholder rows are always
// upgradeable; 'manual'/'enriched' rows must be protected in Go by re-reading
// the existing row inside the ingest transaction when in doubt.
func (q *Queries) UpsertBillStub(ctx context.Context, arg UpsertBillStubParams) error {
	_, err := q.db.ExecContext(ctx, upsertBillStub,
		arg.ID,
		arg.Title,
		arg.TitleSource,
		arg.TitleDate,
	)
	return err
}
