// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: candidates.sql

package database

import (
	"context"
	"database/sql"
)

const enqueueCandidate = `-- name: EnqueueCandidate :exec
INSERT INTO votation_candidates (chamber_id, external_id, source)
VALUES (?, ?, ?)
ON CONFLICT DO NOTHING
`

type EnqueueCandidateParams struct {
	ChamberID  string `json:"chamber_id"`
	ExternalID string `json:"external_id"`
	Source     string `json:"source"`
}

func (q *Queries) EnqueueCandidate(ctx context.Context, arg EnqueueCandidateParams) error {
	_, err := q.db.ExecContext(ctx, enqueueCandidate, arg.ChamberID, arg.ExternalID, arg.Source)
	return err
}

const failCandidate = `-- name: FailCandidate :exec
UPDATE votation_candidates SET
    attempts = attempts + 1, last_error = ?
WHERE chamber_id = ? AND external_id = ?
`

type FailCandidateParams struct {
	LastError  sql.NullString `json:"last_error"`
	ChamberID  string         `json:"chamber_id"`
	ExternalID string         `json:"external_id"`
}

func (q *Queries) FailCandidate(ctx context.Context, arg FailCandidateParams) error {
	_, err := q.db.ExecContext(ctx, failCandidate, arg.LastError, arg.ChamberID, arg.ExternalID)
	return err
}

const markCandidateFetched = `-- name: MarkCandidateFetched :exec
UPDATE votation_candidates SET fetched_at = datetime('now') WHERE fetched_at IS NULL
`

func (q *Queries) MarkCandidateFetched(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, markCandidateFetched)
	return err
}

const pendingCandidates = `-- name: PendingCandidates :many
SELECT chamber_id, external_id, source, discovered_at, fetched_at, attempts, last_error FROM votation_candidates
WHERE fetched_at IS NULL AND attempts < 5
ORDER BY discovered_at
LIMIT ?
`

func (q *Queries) PendingCandidates(ctx context.Context, limit int64) ([]VotationCandidate, error) {
	rows, err := q.db.QueryContext(ctx, pendingCandidates, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VotationCandidate{}
	for rows.Next() {
		var i VotationCandidate
		if err := rows.Scan(
			&i.ChamberID,
			&i.ExternalID,
			&i.Source,
			&i.DiscoveredAt,
			&i.FetchedAt,
			&i.Attempts,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
