// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: individual_votes.sql

package database

import (
	"context"
	"database/sql"
)

const countRepresentativeVotes = `-- name: CountRepresentativeVotes :one
SELECT COUNT(*) FROM individual_votes WHERE representative_id = ?
`

func (q *Queries) CountRepresentativeVotes(ctx context.Context, representativeID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRepresentativeVotes, representativeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteVotesByVotation = `-- name: DeleteVotesByVotation :exec
DELETE FROM individual_votes WHERE votation_id = ?
`

func (q *Queries) DeleteVotesByVotation(ctx context.Context, votationID int64) error {
	_, err := q.db.ExecContext(ctx, deleteVotesByVotation, votationID)
	return err
}

const getRepresentativeVotingHistory = `-- name: GetRepresentativeVotingHistory :many
SELECT iv.votation_id, iv.representative_id, iv.vote, iv.vote_raw, v.date, v.subject, v.result, v.bill_id
FROM individual_votes iv
JOIN votations v ON v.id = iv.votation_id
WHERE iv.representative_id = ?
ORDER BY v.date DESC LIMIT ? OFFSET ?
`

type GetRepresentativeVotingHistoryParams struct {
	RepresentativeID int64 `json:"representative_id"`
	Limit            int64 `json:"limit"`
	Offset           int64 `json:"offset"`
}

type GetRepresentativeVotingHistoryRow struct {
	VotationID       int64          `json:"votation_id"`
	RepresentativeID int64          `json:"representative_id"`
	Vote             string         `json:"vote"`
	VoteRaw          string         `json:"vote_raw"`
	Date             string         `json:"date"`
	Subject          sql.NullString `json:"subject"`
	Result           sql.NullString `json:"result"`
	BillID           sql.NullString `json:"bill_id"`
}

func (q *Queries) GetRepresentativeVotingHistory(ctx context.Context, arg GetRepresentativeVotingHistoryParams) ([]GetRepresentativeVotingHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getRepresentativeVotingHistory, arg.RepresentativeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRepresentativeVotingHistoryRow{}
	for rows.Next() {
		var i GetRepresentativeVotingHistoryRow
		if err := rows.Scan(
			&i.VotationID,
			&i.RepresentativeID,
			&i.Vote,
			&i.VoteRaw,
			&i.Date,
			&i.Subject,
			&i.Result,
			&i.BillID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVoteCounts = `-- name: GetVoteCounts :many
SELECT vote, COUNT(*) AS n FROM individual_votes
WHERE votation_id = ? GROUP BY vote
`

type GetVoteCountsRow struct {
	Vote string `json:"vote"`
	N    int64  `json:"n"`
}

// Audit totals cross-check: count per normalized value.
func (q *Queries) GetVoteCounts(ctx context.Context, votationID int64) ([]GetVoteCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, getVoteCounts, votationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVoteCountsRow{}
	for rows.Next() {
		var i GetVoteCountsRow
		if err := rows.Scan(&i.Vote, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVotesByVotation = `-- name: GetVotesByVotation :many
SELECT iv.vote, iv.vote_raw,
       r.id AS rep_id, r.external_id, r.first_name, r.last_name, r.second_last_name,
       COALESCE(p.short_name, 'sin-partido') AS party_short,
       COALESCE(p.name, 'Sin partido') AS party_name,
       COALESCE(p.color, '#808080') AS party_color,
       rp.id IS NOT NULL AS affiliated
FROM individual_votes iv
JOIN representatives r ON r.id = iv.representative_id
LEFT JOIN representative_parties rp
    ON rp.representative_id = r.id
   AND rp.start_date <= (SELECT CASE WHEN vote_date='0000-00-00' THEN '' ELSE vote_date END FROM votations WHERE id = iv.votation_id)
   AND (rp.end_date IS NULL OR rp.end_date >= (SELECT vote_date FROM votations WHERE id = iv.votation_id))
LEFT JOIN parties p ON p.id = rp.party_id
WHERE iv.votation_id = ?
ORDER BY party_name, r.last_name
`

type GetVotesByVotationRow struct {
	Vote           string `json:"vote"`
	VoteRaw        string `json:"vote_raw"`
	RepID          int64  `json:"rep_id"`
	ExternalID     string `json:"external_id"`
	FirstName      string `json:"first_name"`
	LastName       string `json:"last_name"`
	SecondLastName string `json:"second_last_name"`
	PartyShort     string `json:"party_short"`
	PartyName      string `json:"party_name"`
	PartyColor     string `json:"party_color"`
	Affiliated     bool   `json:"affiliated"`
}

func (q *Queries) GetVotesByVotation(ctx context.Context, votationID int64) ([]GetVotesByVotationRow, error) {
	rows, err := q.db.QueryContext(ctx, getVotesByVotation, votationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVotesByVotationRow{}
	for rows.Next() {
		var i GetVotesByVotationRow
		if err := rows.Scan(
			&i.Vote,
			&i.VoteRaw,
			&i.RepID,
			&i.ExternalID,
			&i.FirstName,
			&i.LastName,
			&i.SecondLastName,
			&i.PartyShort,
			&i.PartyName,
			&i.PartyColor,
			&i.Affiliated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertVote = `-- name: InsertVote :exec
INSERT INTO individual_votes (votation_id, representative_id, vote, vote_raw)
VALUES (?, ?, ?, ?)
ON CONFLICT (votation_id, representative_id) DO UPDATE SET
    vote = excluded.vote, vote_raw = excluded.vote_raw
`

type InsertVoteParams struct {
	VotationID       int64  `json:"votation_id"`
	RepresentativeID int64  `json:"representative_id"`
	Vote             string `json:"vote"`
	VoteRaw          string `json:"vote_raw"`
}

func (q *Queries) InsertVote(ctx context.Context, arg InsertVoteParams) error {
	_, err := q.db.ExecContext(ctx, insertVote,
		arg.VotationID,
		arg.RepresentativeID,
		arg.Vote,
		arg.VoteRaw,
	)
	return err
}

const upsertPareoVote = `-- name: UpsertPareoVote :exec
INSERT INTO individual_votes (votation_id, representative_id, vote, vote_raw)
VALUES (?, ?, 'paired', ?)
ON CONFLICT (votation_id, representative_id) DO UPDATE SET vote = 'paired'
`

type UpsertPareoVoteParams struct {
	VotationID       int64  `json:"votation_id"`
	RepresentativeID int64  `json:"representative_id"`
	VoteRaw          string `json:"vote_raw"`
}

// Override pass: Pareos membership beats an explicit `No Vota` row. Keeping
// the existing row's vote_raw preserves the original explicit text; rows
// created by the pareo pass itself get vote_raw = 'Pareo' from the ?3 arg.
func (q *Queries) UpsertPareoVote(ctx context.Context, arg UpsertPareoVoteParams) error {
	_, err := q.db.ExecContext(ctx, upsertPareoVote, arg.VotationID, arg.RepresentativeID, arg.VoteRaw)
	return err
}
