// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

type Bill struct {
	ID          string         `json:"id"`
	Title       string         `json:"title"`
	TitleSource string         `json:"title_source"`
	TitleDate   sql.NullString `json:"title_date"`
	Status      sql.NullString `json:"status"`
	LawNumber   sql.NullString `json:"law_number"`
	FiledDate   sql.NullString `json:"filed_date"`
}

type Chamber struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type IndividualVote struct {
	VotationID       int64  `json:"votation_id"`
	RepresentativeID int64  `json:"representative_id"`
	Vote             string `json:"vote"`
	VoteRaw          string `json:"vote_raw"`
}

type Party struct {
	ID        int64  `json:"id"`
	ShortName string `json:"short_name"`
	Name      string `json:"name"`
	Color     string `json:"color"`
}

type Representative struct {
	ID             int64          `json:"id"`
	ChamberID      string         `json:"chamber_id"`
	ExternalID     string         `json:"external_id"`
	FirstName      string         `json:"first_name"`
	LastName       string         `json:"last_name"`
	SecondLastName string         `json:"second_last_name"`
	Gender         sql.NullString `json:"gender"`
	BirthDate      sql.NullString `json:"birth_date"`
	Active         int64          `json:"active"`
}

type RepresentativeParty struct {
	ID               int64          `json:"id"`
	RepresentativeID int64          `json:"representative_id"`
	PartyID          int64          `json:"party_id"`
	StartDate        string         `json:"start_date"`
	EndDate          sql.NullString `json:"end_date"`
	Source           string         `json:"source"`
}

type Session struct {
	ID         int64          `json:"id"`
	ChamberID  string         `json:"chamber_id"`
	ExternalID string         `json:"external_id"`
	Number     int64          `json:"number"`
	Date       string         `json:"date"`
	Type       sql.NullString `json:"type"`
}

type SyncMetadatum struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}

type Votation struct {
	ID              int64          `json:"id"`
	ChamberID       string         `json:"chamber_id"`
	ExternalID      string         `json:"external_id"`
	SessionID       sql.NullInt64  `json:"session_id"`
	BillID          sql.NullString `json:"bill_id"`
	Date            string         `json:"date"`
	VoteDate        string         `json:"vote_date"`
	Subject         sql.NullString `json:"subject"`
	VoteType        sql.NullString `json:"vote_type"`
	Result          sql.NullString `json:"result"`
	QuorumType      sql.NullString `json:"quorum_type"`
	LegislativeStep sql.NullString `json:"legislative_step"`
	TotalYes        int64          `json:"total_yes"`
	TotalNo         int64          `json:"total_no"`
	TotalAbstain    int64          `json:"total_abstain"`
	TotalDispensed  int64          `json:"total_dispensed"`
}

type VotationCandidate struct {
	ChamberID    string         `json:"chamber_id"`
	ExternalID   string         `json:"external_id"`
	Source       string         `json:"source"`
	DiscoveredAt string         `json:"discovered_at"`
	FetchedAt    sql.NullString `json:"fetched_at"`
	Attempts     int64          `json:"attempts"`
	LastError    sql.NullString `json:"last_error"`
}
