// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: parties.sql

package database

import (
	"context"
	"database/sql"
)

const affiliationGaps = `-- name: AffiliationGaps :many
SELECT DISTINCT iv.representative_id AS rid
FROM individual_votes iv
LEFT JOIN representative_parties rp ON rp.representative_id = iv.representative_id
WHERE rp.id IS NULL
`

// Deputies with votes but no party-at-date or party membership at all.
func (q *Queries) AffiliationGaps(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, affiliationGaps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var rid int64
		if err := rows.Scan(&rid); err != nil {
			return nil, err
		}
		items = append(items, rid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCuratedAffiliations = `-- name: DeleteCuratedAffiliations :exec
DELETE FROM representative_parties WHERE source = 'curated'
`

func (q *Queries) DeleteCuratedAffiliations(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteCuratedAffiliations)
	return err
}

const getParty = `-- name: GetParty :one
SELECT id, short_name, name, color FROM parties WHERE id = ?
`

func (q *Queries) GetParty(ctx context.Context, id int64) (Party, error) {
	row := q.db.QueryRowContext(ctx, getParty, id)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.ShortName,
		&i.Name,
		&i.Color,
	)
	return i, err
}

const getPartyByShortName = `-- name: GetPartyByShortName :one
SELECT id, short_name, name, color FROM parties WHERE short_name = ?
`

func (q *Queries) GetPartyByShortName(ctx context.Context, shortName string) (Party, error) {
	row := q.db.QueryRowContext(ctx, getPartyByShortName, shortName)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.ShortName,
		&i.Name,
		&i.Color,
	)
	return i, err
}

const insertAffiliation = `-- name: InsertAffiliation :exec
INSERT INTO representative_parties (representative_id, party_id, start_date, end_date, source)
VALUES (?, ?, ?, ?, 'curated')
`

type InsertAffiliationParams struct {
	RepresentativeID int64          `json:"representative_id"`
	PartyID          int64          `json:"party_id"`
	StartDate        string         `json:"start_date"`
	EndDate          sql.NullString `json:"end_date"`
}

func (q *Queries) InsertAffiliation(ctx context.Context, arg InsertAffiliationParams) error {
	_, err := q.db.ExecContext(ctx, insertAffiliation,
		arg.RepresentativeID,
		arg.PartyID,
		arg.StartDate,
		arg.EndDate,
	)
	return err
}

const listParties = `-- name: ListParties :many
SELECT id, short_name, name, color FROM parties ORDER BY name
`

func (q *Queries) ListParties(ctx context.Context) ([]Party, error) {
	rows, err := q.db.QueryContext(ctx, listParties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Party{}
	for rows.Next() {
		var i Party
		if err := rows.Scan(
			&i.ID,
			&i.ShortName,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const partyMembers = `-- name: PartyMembers :many
SELECT r.id, r.chamber_id, r.external_id, r.first_name, r.last_name, r.second_last_name, r.gender, r.birth_date, r.active, p.short_name AS party_short, p.name AS party_name
FROM representatives r
JOIN representative_parties rp ON rp.representative_id = r.id AND rp.end_date IS NULL
JOIN parties p ON p.id = rp.party_id
WHERE rp.party_id = ?
ORDER BY r.active DESC, r.last_name
`

type PartyMembersRow struct {
	ID             int64          `json:"id"`
	ChamberID      string         `json:"chamber_id"`
	ExternalID     string         `json:"external_id"`
	FirstName      string         `json:"first_name"`
	LastName       string         `json:"last_name"`
	SecondLastName string         `json:"second_last_name"`
	Gender         sql.NullString `json:"gender"`
	BirthDate      sql.NullString `json:"birth_date"`
	Active         int64          `json:"active"`
	PartyShort     string         `json:"party_short"`
	PartyName      string         `json:"party_name"`
}

// Current members of one party (membership with end_date IS NULL).
func (q *Queries) PartyMembers(ctx context.Context, partyID int64) ([]PartyMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, partyMembers, partyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PartyMembersRow{}
	for rows.Next() {
		var i PartyMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.ChamberID,
			&i.ExternalID,
			&i.FirstName,
			&i.LastName,
			&i.SecondLastName,
			&i.Gender,
			&i.BirthDate,
			&i.Active,
			&i.PartyShort,
			&i.PartyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertParty = `-- name: UpsertParty :exec
INSERT INTO parties (short_name, name, color) VALUES (?, ?, ?)
ON CONFLICT (short_name) DO UPDATE SET
    name = excluded.name, color = excluded.color
`

type UpsertPartyParams struct {
	ShortName string `json:"short_name"`
	Name      string `json:"name"`
	Color     string `json:"color"`
}

func (q *Queries) UpsertParty(ctx context.Context, arg UpsertPartyParams) error {
	_, err := q.db.ExecContext(ctx, upsertParty, arg.ShortName, arg.Name, arg.Color)
	return err
}
