// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
	"database/sql"
)

type Querier interface {
	// Single-writer lease: compare-and-swap against an empty/expired value.
	// The caller generates owner+expiry; 0 rows = someone else holds it.
	AcquireSyncLock(ctx context.Context, value string) (int64, error)
	// Deputies with votes but no party-at-date or party membership at all.
	AffiliationGaps(ctx context.Context) ([]int64, error)
	CountBills(ctx context.Context, id string) (int64, error)
	CountRepresentativeVotes(ctx context.Context, representativeID int64) (int64, error)
	CountRepresentatives(ctx context.Context, arg CountRepresentativesParams) (int64, error)
	CountVotations(ctx context.Context, arg CountVotationsParams) (int64, error)
	DeleteCuratedAffiliations(ctx context.Context) error
	DeleteVotesByVotation(ctx context.Context, votationID int64) error
	EnqueueCandidate(ctx context.Context, arg EnqueueCandidateParams) error
	EnrichRepresentative(ctx context.Context, arg EnrichRepresentativeParams) error
	FailCandidate(ctx context.Context, arg FailCandidateParams) error
	GetBill(ctx context.Context, id string) (Bill, error)
	// Per-(party, votation) CAST-vote counts in a chamber + [from,to] vote_date
	// window (empty string = open bound), optional party filter (0 = all).
	// Cast votes only (yes/no/abstain): absent/dispensed/paired are not
	// positions and are excluded from every Rice aggregate (DESIGN.md gap 8).
	GetCohesionRows(ctx context.Context, arg GetCohesionRowsParams) ([]GetCohesionRowsRow, error)
	// Rep-level cast votes with party-at-date in the window. Feeds the
	// loyalty/'rebels' arithmetic: per (party, votation) modal vote across ALL
	// party members, then each rep's vote compared against it.
	GetLoyaltyRows(ctx context.Context, arg GetLoyaltyRowsParams) ([]GetLoyaltyRowsRow, error)
	GetMinVoteDate(ctx context.Context) (string, error)
	// Pairwise same-cast-vote counts for the alignment matrix: deputy pairs that
	// were both present (cast) on the same votation, how often they agreed.
	// Optional party filter applies party-at-date to BOTH pair members.
	GetPairAgreementRows(ctx context.Context, arg GetPairAgreementRowsParams) ([]GetPairAgreementRowsRow, error)
	GetParty(ctx context.Context, id int64) (Party, error)
	GetPartyByShortName(ctx context.Context, shortName string) (Party, error)
	// Per-party vote counts for one votation (party-at-date join). Consumed by
	// the breakdown chart and, in Phase 2, the Rice-cohesion arithmetic.
	GetPartyVoteCounts(ctx context.Context, votationID int64) ([]GetPartyVoteCountsRow, error)
	GetRepresentative(ctx context.Context, id int64) (GetRepresentativeRow, error)
	GetRepresentativeInternalID(ctx context.Context, arg GetRepresentativeInternalIDParams) (int64, error)
	// Display names for an explicit ID set (alignment pairs fetch names for the
	// reps actually shown instead of scanning the whole table).
	GetRepresentativeNames(ctx context.Context, repIds []int64) ([]GetRepresentativeNamesRow, error)
	GetRepresentativeVotingHistory(ctx context.Context, arg GetRepresentativeVotingHistoryParams) ([]GetRepresentativeVotingHistoryRow, error)
	GetSyncValue(ctx context.Context, key string) (string, error)
	GetVotation(ctx context.Context, id int64) (Votation, error)
	GetVotationByExternalID(ctx context.Context, arg GetVotationByExternalIDParams) (Votation, error)
	GetVotationsByBill(ctx context.Context, billID sql.NullString) ([]Votation, error)
	// Audit totals cross-check: count per normalized value.
	GetVoteCounts(ctx context.Context, votationID int64) ([]GetVoteCountsRow, error)
	GetVotesByVotation(ctx context.Context, votationID int64) ([]GetVotesByVotationRow, error)
	InsertAffiliation(ctx context.Context, arg InsertAffiliationParams) error
	InsertVote(ctx context.Context, arg InsertVoteParams) error
	// matches with a caller-supplied pattern ('%term%' built in Go)
	ListBills(ctx context.Context, arg ListBillsParams) ([]Bill, error)
	ListParties(ctx context.Context) ([]Party, error)
	ListRepresentatives(ctx context.Context, arg ListRepresentativesParams) ([]ListRepresentativesRow, error)
	ListVotations(ctx context.Context, arg ListVotationsParams) ([]ListVotationsRow, error)
	MarkCandidateFetched(ctx context.Context) error
	// Current members of one party (membership with end_date IS NULL).
	PartyMembers(ctx context.Context, partyID int64) ([]PartyMembersRow, error)
	PendingCandidates(ctx context.Context, limit int64) ([]VotationCandidate, error)
	ReleaseSyncLock(ctx context.Context) error
	SetRepresentativeActive(ctx context.Context, arg SetRepresentativeActiveParams) error
	// Called by SyncDeputies before granting active via the vigentes set.
	SetRepresentativesInactive(ctx context.Context, chamberID string) error
	// Title upgrade policy is decided in Go (most-recent-votation Articulo wins);
	// the caller passes the chosen title/source/date. Placeholder rows are always
	// upgradeable; 'manual'/'enriched' rows must be protected in Go by re-reading
	// the existing row inside the ingest transaction when in doubt.
	UpsertBillStub(ctx context.Context, arg UpsertBillStubParams) error
	// Override pass: Pareos membership beats an explicit `No Vota` row. Keeping
	// the existing row's vote_raw preserves the original explicit text; rows
	// created by the pareo pass itself get vote_raw = 'Pareo' from the ?3 arg.
	UpsertPareoVote(ctx context.Context, arg UpsertPareoVoteParams) error
	UpsertParty(ctx context.Context, arg UpsertPartyParams) error
	// DO NOTHING + RETURNING returns the existing row id on conflict (idiomatic
	// SQLite reconcile used by stub creation and enrichment alike).
	UpsertRepresentative(ctx context.Context, arg UpsertRepresentativeParams) (int64, error)
	// Used by BOTH the vote-row stub path and SyncDeputies enrichment; the
	// enrich fields (gender/birth_date) are COALESCE-time-nullable.
	UpsertRepresentativeFull(ctx context.Context, arg UpsertRepresentativeFullParams) (int64, error)
	UpsertSession(ctx context.Context, arg UpsertSessionParams) (int64, error)
	UpsertSyncValue(ctx context.Context, arg UpsertSyncValueParams) error
	UpsertVotation(ctx context.Context, arg UpsertVotationParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
