// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: representatives.sql

package database

import (
	"context"
	"database/sql"
)

const countRepresentatives = `-- name: CountRepresentatives :one
SELECT COUNT(*) FROM representatives
WHERE (? = '' OR chamber_id = ?)
`

type CountRepresentativesParams struct {
	Column1   interface{} `json:"column_1"`
	ChamberID string      `json:"chamber_id"`
}

func (q *Queries) CountRepresentatives(ctx context.Context, arg CountRepresentativesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRepresentatives, arg.Column1, arg.ChamberID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const enrichRepresentative = `-- name: EnrichRepresentative :exec
UPDATE representatives SET
    gender = COALESCE(?, gender),
    birth_date = COALESCE(?, birth_date)
WHERE chamber_id = ? AND external_id = ?
`

type EnrichRepresentativeParams struct {
	Gender     sql.NullString `json:"gender"`
	BirthDate  sql.NullString `json:"birth_date"`
	ChamberID  string         `json:"chamber_id"`
	ExternalID string         `json:"external_id"`
}

func (q *Queries) EnrichRepresentative(ctx context.Context, arg EnrichRepresentativeParams) error {
	_, err := q.db.ExecContext(ctx, enrichRepresentative,
		arg.Gender,
		arg.BirthDate,
		arg.ChamberID,
		arg.ExternalID,
	)
	return err
}

const getRepresentative = `-- name: GetRepresentative :one
SELECT r.id, r.chamber_id, r.external_id, r.first_name, r.last_name, r.second_last_name, r.gender, r.birth_date, r.active, COALESCE(p.short_name, 'sin-partido') AS party_short, COALESCE(p.name, 'Sin partido') AS party_name
FROM representatives r
LEFT JOIN representative_parties rp ON rp.representative_id = r.id AND rp.end_date IS NULL
LEFT JOIN parties p ON p.id = rp.party_id
WHERE r.id = ?
`

type GetRepresentativeRow struct {
	ID             int64          `json:"id"`
	ChamberID      string         `json:"chamber_id"`
	ExternalID     string         `json:"external_id"`
	FirstName      string         `json:"first_name"`
	LastName       string         `json:"last_name"`
	SecondLastName string         `json:"second_last_name"`
	Gender         sql.NullString `json:"gender"`
	BirthDate      sql.NullString `json:"birth_date"`
	Active         int64          `json:"active"`
	PartyShort     string         `json:"party_short"`
	PartyName      string         `json:"party_name"`
}

func (q *Queries) GetRepresentative(ctx context.Context, id int64) (GetRepresentativeRow, error) {
	row := q.db.QueryRowContext(ctx, getRepresentative, id)
	var i GetRepresentativeRow
	err := row.Scan(
		&i.ID,
		&i.ChamberID,
		&i.ExternalID,
		&i.FirstName,
		&i.LastName,
		&i.SecondLastName,
		&i.Gender,
		&i.BirthDate,
		&i.Active,
		&i.PartyShort,
		&i.PartyName,
	)
	return i, err
}

const getRepresentativeInternalID = `-- name: GetRepresentativeInternalID :one
SELECT id FROM representatives WHERE chamber_id = ? AND external_id = ?
`

type GetRepresentativeInternalIDParams struct {
	ChamberID  string `json:"chamber_id"`
	ExternalID string `json:"external_id"`
}

func (q *Queries) GetRepresentativeInternalID(ctx context.Context, arg GetRepresentativeInternalIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getRepresentativeInternalID, arg.ChamberID, arg.ExternalID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listRepresentatives = `-- name: ListRepresentatives :many
SELECT r.id, r.chamber_id, r.external_id, r.first_name, r.last_name, r.second_last_name, r.gender, r.birth_date, r.active, p.short_name AS party_short, p.name AS party_name
FROM representatives r
LEFT JOIN representative_parties rp ON rp.representative_id = r.id AND rp.end_date IS NULL
LEFT JOIN parties p ON p.id = rp.party_id
WHERE (? = '' OR r.chamber_id = ?)
ORDER BY r.active DESC, r.last_name
LIMIT ? OFFSET ?
`

type ListRepresentativesParams struct {
	Column1   interface{} `json:"column_1"`
	ChamberID string      `json:"chamber_id"`
	Limit     int64       `json:"limit"`
	Offset    int64       `json:"offset"`
}

type ListRepresentativesRow struct {
	ID             int64          `json:"id"`
	ChamberID      string         `json:"chamber_id"`
	ExternalID     string         `json:"external_id"`
	FirstName      string         `json:"first_name"`
	LastName       string         `json:"last_name"`
	SecondLastName string         `json:"second_last_name"`
	Gender         sql.NullString `json:"gender"`
	BirthDate      sql.NullString `json:"birth_date"`
	Active         int64          `json:"active"`
	PartyShort     sql.NullString `json:"party_short"`
	PartyName      sql.NullString `json:"party_name"`
}

func (q *Queries) ListRepresentatives(ctx context.Context, arg ListRepresentativesParams) ([]ListRepresentativesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRepresentatives,
		arg.Column1,
		arg.ChamberID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRepresentativesRow{}
	for rows.Next() {
		var i ListRepresentativesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChamberID,
			&i.ExternalID,
			&i.FirstName,
			&i.LastName,
			&i.SecondLastName,
			&i.Gender,
			&i.BirthDate,
			&i.Active,
			&i.PartyShort,
			&i.PartyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRepresentativeActive = `-- name: SetRepresentativeActive :exec
UPDATE representatives SET active = 1 WHERE chamber_id = ? AND external_id = ?
`

type SetRepresentativeActiveParams struct {
	ChamberID  string `json:"chamber_id"`
	ExternalID string `json:"external_id"`
}

func (q *Queries) SetRepresentativeActive(ctx context.Context, arg SetRepresentativeActiveParams) error {
	_, err := q.db.ExecContext(ctx, setRepresentativeActive, arg.ChamberID, arg.ExternalID)
	return err
}

const setRepresentativesInactive = `-- name: SetRepresentativesInactive :exec
UPDATE representatives SET active = 0 WHERE chamber_id = ?
`

// Called by SyncDeputies before granting active via the vigentes set.
func (q *Queries) SetRepresentativesInactive(ctx context.Context, chamberID string) error {
	_, err := q.db.ExecContext(ctx, setRepresentativesInactive, chamberID)
	return err
}

const upsertRepresentative = `-- name: UpsertRepresentative :one
INSERT INTO representatives (chamber_id, external_id, first_name, last_name, second_last_name)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (chamber_id, external_id) DO UPDATE SET
    first_name = COALESCE(NULLIF(excluded.first_name, ''), representatives.first_name),
    last_name = COALESCE(NULLIF(excluded.last_name, ''), representatives.last_name),
    second_last_name = COALESCE(NULLIF(excluded.second_last_name, ''), representatives.second_last_name)
RETURNING id
`

type UpsertRepresentativeParams struct {
	ChamberID      string `json:"chamber_id"`
	ExternalID     string `json:"external_id"`
	FirstName      string `json:"first_name"`
	LastName       string `json:"last_name"`
	SecondLastName string `json:"second_last_name"`
}

// DO NOTHING + RETURNING returns the existing row id on conflict (idiomatic
// SQLite reconcile used by stub creation and enrichment alike).
func (q *Queries) UpsertRepresentative(ctx context.Context, arg UpsertRepresentativeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertRepresentative,
		arg.ChamberID,
		arg.ExternalID,
		arg.FirstName,
		arg.LastName,
		arg.SecondLastName,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertRepresentativeFull = `-- name: UpsertRepresentativeFull :one
INSERT INTO representatives (chamber_id, external_id, first_name, last_name, second_last_name, gender, birth_date)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (chamber_id, external_id) DO UPDATE SET
    first_name = COALESCE(NULLIF(excluded.first_name, ''), representatives.first_name),
    last_name = COALESCE(NULLIF(excluded.last_name, ''), representatives.last_name),
    second_last_name = COALESCE(NULLIF(excluded.second_last_name, ''), representatives.second_last_name),
    gender = COALESCE(excluded.gender, representatives.gender),
    birth_date = COALESCE(excluded.birth_date, representatives.birth_date)
RETURNING id
`

type UpsertRepresentativeFullParams struct {
	ChamberID      string         `json:"chamber_id"`
	ExternalID     string         `json:"external_id"`
	FirstName      string         `json:"first_name"`
	LastName       string         `json:"last_name"`
	SecondLastName string         `json:"second_last_name"`
	Gender         sql.NullString `json:"gender"`
	BirthDate      sql.NullString `json:"birth_date"`
}

// Used by BOTH the vote-row stub path and SyncDeputies enrichment; the
// enrich fields (gender/birth_date) are COALESCE-time-nullable.
func (q *Queries) UpsertRepresentativeFull(ctx context.Context, arg UpsertRepresentativeFullParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertRepresentativeFull,
		arg.ChamberID,
		arg.ExternalID,
		arg.FirstName,
		arg.LastName,
		arg.SecondLastName,
		arg.Gender,
		arg.BirthDate,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
