// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package database

import (
	"context"
	"database/sql"
)

const upsertSession = `-- name: UpsertSession :one
INSERT INTO sessions (chamber_id, external_id, number, date, type)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (chamber_id, external_id) DO UPDATE SET
    number = excluded.number, date = excluded.date, type = excluded.type
RETURNING id
`

type UpsertSessionParams struct {
	ChamberID  string         `json:"chamber_id"`
	ExternalID string         `json:"external_id"`
	Number     int64          `json:"number"`
	Date       string         `json:"date"`
	Type       sql.NullString `json:"type"`
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertSession,
		arg.ChamberID,
		arg.ExternalID,
		arg.Number,
		arg.Date,
		arg.Type,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
