// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package database

import (
	"context"
)

const acquireSyncLock = `-- name: AcquireSyncLock :execrows
UPDATE sync_metadata SET value = ?, updated_at = datetime('now')
WHERE key = 'camara.sync_lock'
  AND (value = ''
       OR CAST(SUBSTR(value, INSTR(value, '|') + 1) AS INTEGER) < CAST(strftime('%s', 'now') AS INTEGER))
`

// Single-writer lease: compare-and-swap against an empty/expired value.
// The caller generates owner+expiry; 0 rows = someone else holds it.
func (q *Queries) AcquireSyncLock(ctx context.Context, value string) (int64, error) {
	result, err := q.db.ExecContext(ctx, acquireSyncLock, value)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMinVoteDate = `-- name: GetMinVoteDate :one
SELECT CAST(CASE WHEN MIN(vote_date) IS NULL THEN ''
            WHEN MIN(vote_date) = '0000-00-00' THEN ''
            ELSE MIN(vote_date) END AS TEXT) AS min_vote_date
FROM votations WHERE chamber_id = 'camara'
`

func (q *Queries) GetMinVoteDate(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getMinVoteDate)
	var min_vote_date string
	err := row.Scan(&min_vote_date)
	return min_vote_date, err
}

const getSyncValue = `-- name: GetSyncValue :one
SELECT value FROM sync_metadata WHERE key = ?
`

func (q *Queries) GetSyncValue(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSyncValue, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const releaseSyncLock = `-- name: ReleaseSyncLock :exec
UPDATE sync_metadata SET value = '' WHERE key = 'camara.sync_lock'
`

func (q *Queries) ReleaseSyncLock(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, releaseSyncLock)
	return err
}

const upsertSyncValue = `-- name: UpsertSyncValue :exec
INSERT INTO sync_metadata (key, value, updated_at) VALUES (?, ?, datetime('now'))
ON CONFLICT (key) DO UPDATE SET value = excluded.value, updated_at = datetime('now')
`

type UpsertSyncValueParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertSyncValue(ctx context.Context, arg UpsertSyncValueParams) error {
	_, err := q.db.ExecContext(ctx, upsertSyncValue, arg.Key, arg.Value)
	return err
}
