// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: votations.sql

package database

import (
	"context"
	"database/sql"
)

const countVotations = `-- name: CountVotations :one
SELECT COUNT(*) FROM votations
WHERE (? = '' OR chamber_id = ?)
  AND (? = '' OR result = ?)
  AND (? = '' OR bill_id = ?)
`

type CountVotationsParams struct {
	Column1   interface{}    `json:"column_1"`
	ChamberID string         `json:"chamber_id"`
	Column3   interface{}    `json:"column_3"`
	Result    sql.NullString `json:"result"`
	Column5   interface{}    `json:"column_5"`
	BillID    sql.NullString `json:"bill_id"`
}

func (q *Queries) CountVotations(ctx context.Context, arg CountVotationsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVotations,
		arg.Column1,
		arg.ChamberID,
		arg.Column3,
		arg.Result,
		arg.Column5,
		arg.BillID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getVotation = `-- name: GetVotation :one
SELECT id, chamber_id, external_id, session_id, bill_id, date, vote_date, subject, vote_type, result, quorum_type, legislative_step, total_yes, total_no, total_abstain, total_dispensed FROM votations WHERE id = ?
`

func (q *Queries) GetVotation(ctx context.Context, id int64) (Votation, error) {
	row := q.db.QueryRowContext(ctx, getVotation, id)
	var i Votation
	err := row.Scan(
		&i.ID,
		&i.ChamberID,
		&i.ExternalID,
		&i.SessionID,
		&i.BillID,
		&i.Date,
		&i.VoteDate,
		&i.Subject,
		&i.VoteType,
		&i.Result,
		&i.QuorumType,
		&i.LegislativeStep,
		&i.TotalYes,
		&i.TotalNo,
		&i.TotalAbstain,
		&i.TotalDispensed,
	)
	return i, err
}

const getVotationByExternalID = `-- name: GetVotationByExternalID :one
SELECT id, chamber_id, external_id, session_id, bill_id, date, vote_date, subject, vote_type, result, quorum_type, legislative_step, total_yes, total_no, total_abstain, total_dispensed FROM votations WHERE chamber_id = ? AND external_id = ?
`

type GetVotationByExternalIDParams struct {
	ChamberID  string `json:"chamber_id"`
	ExternalID string `json:"external_id"`
}

func (q *Queries) GetVotationByExternalID(ctx context.Context, arg GetVotationByExternalIDParams) (Votation, error) {
	row := q.db.QueryRowContext(ctx, getVotationByExternalID, arg.ChamberID, arg.ExternalID)
	var i Votation
	err := row.Scan(
		&i.ID,
		&i.ChamberID,
		&i.ExternalID,
		&i.SessionID,
		&i.BillID,
		&i.Date,
		&i.VoteDate,
		&i.Subject,
		&i.VoteType,
		&i.Result,
		&i.QuorumType,
		&i.LegislativeStep,
		&i.TotalYes,
		&i.TotalNo,
		&i.TotalAbstain,
		&i.TotalDispensed,
	)
	return i, err
}

const listVotations = `-- name: ListVotations :many
SELECT v.id, v.chamber_id, v.external_id, v.session_id, v.bill_id, v.date, v.vote_date, v.subject, v.vote_type, v.result, v.quorum_type, v.legislative_step, v.total_yes, v.total_no, v.total_abstain, v.total_dispensed, b.title AS bill_title
FROM votations v
LEFT JOIN bills b ON b.id = v.bill_id
WHERE (? = '' OR v.chamber_id = ?)
  AND (? = '' OR v.result = ?)
  AND (? = '' OR v.bill_id = ?)
ORDER BY v.date DESC
LIMIT ? OFFSET ?
`

type ListVotationsParams struct {
	Column1   interface{}    `json:"column_1"`
	ChamberID string         `json:"chamber_id"`
	Column3   interface{}    `json:"column_3"`
	Result    sql.NullString `json:"result"`
	Column5   interface{}    `json:"column_5"`
	BillID    sql.NullString `json:"bill_id"`
	Limit     int64          `json:"limit"`
	Offset    int64          `json:"offset"`
}

type ListVotationsRow struct {
	ID              int64          `json:"id"`
	ChamberID       string         `json:"chamber_id"`
	ExternalID      string         `json:"external_id"`
	SessionID       sql.NullInt64  `json:"session_id"`
	BillID          sql.NullString `json:"bill_id"`
	Date            string         `json:"date"`
	VoteDate        string         `json:"vote_date"`
	Subject         sql.NullString `json:"subject"`
	VoteType        sql.NullString `json:"vote_type"`
	Result          sql.NullString `json:"result"`
	QuorumType      sql.NullString `json:"quorum_type"`
	LegislativeStep sql.NullString `json:"legislative_step"`
	TotalYes        int64          `json:"total_yes"`
	TotalNo         int64          `json:"total_no"`
	TotalAbstain    int64          `json:"total_abstain"`
	TotalDispensed  int64          `json:"total_dispensed"`
	BillTitle       sql.NullString `json:"bill_title"`
}

func (q *Queries) ListVotations(ctx context.Context, arg ListVotationsParams) ([]ListVotationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listVotations,
		arg.Column1,
		arg.ChamberID,
		arg.Column3,
		arg.Result,
		arg.Column5,
		arg.BillID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVotationsRow{}
	for rows.Next() {
		var i ListVotationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ChamberID,
			&i.ExternalID,
			&i.SessionID,
			&i.BillID,
			&i.Date,
			&i.VoteDate,
			&i.Subject,
			&i.VoteType,
			&i.Result,
			&i.QuorumType,
			&i.LegislativeStep,
			&i.TotalYes,
			&i.TotalNo,
			&i.TotalAbstain,
			&i.TotalDispensed,
			&i.BillTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVotation = `-- name: UpsertVotation :one
INSERT INTO votations (
    chamber_id, external_id, session_id, bill_id, date, vote_date,
    subject, vote_type, result, quorum_type, legislative_step,
    total_yes, total_no, total_abstain, total_dispensed
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (chamber_id, external_id) DO UPDATE SET
    session_id = excluded.session_id,
    bill_id = excluded.bill_id,
    date = excluded.date,
    vote_date = excluded.vote_date,
    subject = excluded.subject,
    vote_type = excluded.vote_type,
    result = excluded.result,
    quorum_type = excluded.quorum_type,
    legislative_step = excluded.legislative_step,
    total_yes = excluded.total_yes,
    total_no = excluded.total_no,
    total_abstain = excluded.total_abstain,
    total_dispensed = excluded.total_dispensed
RETURNING id
`

type UpsertVotationParams struct {
	ChamberID       string         `json:"chamber_id"`
	ExternalID      string         `json:"external_id"`
	SessionID       sql.NullInt64  `json:"session_id"`
	BillID          sql.NullString `json:"bill_id"`
	Date            string         `json:"date"`
	VoteDate        string         `json:"vote_date"`
	Subject         sql.NullString `json:"subject"`
	VoteType        sql.NullString `json:"vote_type"`
	Result          sql.NullString `json:"result"`
	QuorumType      sql.NullString `json:"quorum_type"`
	LegislativeStep sql.NullString `json:"legislative_step"`
	TotalYes        int64          `json:"total_yes"`
	TotalNo         int64          `json:"total_no"`
	TotalAbstain    int64          `json:"total_abstain"`
	TotalDispensed  int64          `json:"total_dispensed"`
}

func (q *Queries) UpsertVotation(ctx context.Context, arg UpsertVotationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertVotation,
		arg.ChamberID,
		arg.ExternalID,
		arg.SessionID,
		arg.BillID,
		arg.Date,
		arg.VoteDate,
		arg.Subject,
		arg.VoteType,
		arg.Result,
		arg.QuorumType,
		arg.LegislativeStep,
		arg.TotalYes,
		arg.TotalNo,
		arg.TotalAbstain,
		arg.TotalDispensed,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
